language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

stages:
  - lint
  - race
  - test

jobs:
  include:
    - stage: lint
      go: 1.13.x
      before_script:
        - 'curl -sfL
            https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
            | sh -s v1.21.0'
      script:
        - ./bin/golangci-lint run
    - stage: race
      script:
        - go test ./... -race
      go: 1.13.x
    - stage: test
      script:
        - go test ./... -coverprofile=coverage.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash)
