language: go
go:
  - 1.0.x
  - 1.1.x
  - 1.2.x
  - 1.3.x
  - 1.4.x
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      go: 1.13.x
      before_script:
        - 'curl -sfL
            https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
            | sh -s v1.21.0'
      script:
        - ./bin/golangci-lint run
    - stage: test
      script: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      after_success: bash <(curl -s https://codecov.io/bash)
