language: go
go:
  - 1.11.x
  - 1.12.x

branches:
  only:
    - master

env:
  - GO111MODULE=on

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
