language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

stages:
  - lint
  - test

jobs:
  include:
    - stage: test
      script: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
    - stage: lint
      before_script:
        - 'curl -sfL
            https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
            | sh -s v1.21.0'
      script: ./bin/golangci-lint run
  # exclude:
  #   - stage: lint
  #     go: 1.10.x
