language: go
go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x

arch:
  - amd64
  - arm64

branches:
  only:
    - master

env:
  - GO111MODULE=on

before_script:
  - 'curl -sfL
      https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
      | sh -s v1.31.0'

script:
  - ./bin/golangci-lint run
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
